version: '3.3'

services:

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  #
  # PostgreSQL
  #
  project_postgres:
    container_name: project_postgres
    image: postgres:14.6-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=secret
      - POSTGRES_PORT=5432
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  pgadmin:
    container_name: project_pgadmin
    image: dpage/pgadmin4:latest
    environment:
        PGADMIN_DEFAULT_EMAIL: pythoniste@protonmail.com
        PGADMIN_DEFAULT_PASSWORD: secret
        PGADMIN_LISTEN_PORT: 80
    ports:
        - 8032:80
    volumes:
        - pgadmin_data:/var/lib/pgadmin
        - ./servers.json:/pgadmin4/servers.json
    depends_on:
        - project_postgres
    networks:
      - internal

  #
  # MySQL
  #

  project_mysql:
    container_name: project_mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "13306:3306"
    volumes:
      # - ./conf.d:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  adminer:
    container_name: project_adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8063:8080
    depends_on:
        - project_mysql
    networks:
      - internal

  project_main:
    container_name: project_main
    build:
      context: .
      dockerfile: ./Dockerfile
    command: pserve development.ini
    tty: true
    ports:
     - "6543:6543"
    volumes:
      - ".:/home/pythoniste"
      # - "./pyproject.toml:pyproject.toml"
      # - "./poetry.lock:poetry.lock"
    restart: unless-stopped
    links:
      - project_postgres
    depends_on:
      - project_postgres
    environment:
      - POSTGRES_HOST=project_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=project
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=secret
    networks:
     - internal
     - external

volumes:
  portainer_data:
  postgres_data:
  pgadmin_data:
  mysql_data:

networks:
  internal:
  external:
    external: true
